package net.javols.compiler.view;

import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.CodeBlock;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeName;
import com.squareup.javapoet.TypeSpec;
import com.squareup.javapoet.TypeVariableName;
import net.javols.compiler.Context;
import net.javols.compiler.Parameter;

import java.util.Arrays;
import java.util.Optional;
import java.util.function.Function;

import static javax.lang.model.element.Modifier.PRIVATE;
import static javax.lang.model.element.Modifier.STATIC;

/**
 * Generates the *_Parser class.
 */
public final class GeneratedClass {

  private static final String PROJECT_URL = "https://github.com/h908714124/javols";

  private final Context context;

  private static final TypeVariableName X = TypeVariableName.get("X").withBounds(Throwable.class);

  private static final ParameterizedTypeName S2S = ParameterizedTypeName.get(Function.class, String.class, String.class);
  private static final ParameterizedTypeName S2E = ParameterizedTypeName.get(ClassName.get(Function.class), ClassName.get(String.class), X);

  private final ParameterSpec f = ParameterSpec.builder(S2S, "f").build();
  private final ParameterSpec errMissing = ParameterSpec.builder(S2E, "errMissing").build();

  private GeneratedClass(Context context) {
    this.context = context;
  }

  public static GeneratedClass create(Context context) {
    return new GeneratedClass(context);
  }

  public TypeSpec define() {
    TypeSpec.Builder spec = TypeSpec.classBuilder(context.generatedClass());

    spec.addMethod(parseMethodOverload())
        .addMethod(parseMethod())
        .addMethod(MethodSpec.constructorBuilder().addModifiers(PRIVATE).build());

    spec.addType(Impl.define(context));

    return spec.addModifiers(context.getAccessModifiers())
        .addJavadoc(javadoc()).build();
  }

  private MethodSpec parseMethodOverload() {
    ParameterSpec key = ParameterSpec.builder(String.class, "key").build();
    return MethodSpec.methodBuilder("parse")
        .addParameter(f)
        .addStatement("return parse($N, $N -> new $T($S + $N + $S))", f, key, IllegalArgumentException.class,
            "Missing required key: <", key, ">")
        .returns(context.sourceType())
        .addModifiers(STATIC)
        .addModifiers(context.getAccessModifiers())
        .build();
  }

  private MethodSpec parseMethod() {

    TypeName transformType = ParameterizedTypeName.get(ClassName.get(Function.class),
        TypeName.get(context.transform().inputType()), TypeName.get(context.transform().outputType()));
    ParameterSpec transform = ParameterSpec.builder(transformType, "t").build();
    MethodSpec.Builder spec = MethodSpec.methodBuilder("parse");
    spec.addException(X);
    spec.addTypeVariable(X);
    spec.addStatement("$T $N = $L", transformType, transform, context.transform().transformExpr());
    CodeBlock.Builder args = CodeBlock.builder().add("\n");
    for (int j = 0; j < context.parameters().size(); j++) {
      Parameter param = context.parameters().get(j);
      args.add(extractExpression(param, transform));
      if (j < context.parameters().size() - 1) {
        args.add(",\n");
      }
    }

    return spec.addParameters(Arrays.asList(f, errMissing))
        .addStatement("return new $T($L)", context.implType(), args.build())
        .returns(context.sourceType())
        .addModifiers(STATIC)
        .addModifiers(context.getAccessModifiers())
        .build();
  }

  private CodeBlock extractExpression(Parameter param, ParameterSpec transform) {
    return CodeBlock.builder().add("$T.ofNullable($N.apply($S))", Optional.class, f, param.key())
        .add(".map($N)", transform)
        .add(".map($L)", param.coercion().mapExpr())
        .add(collectExpr(param))
        .build();
  }

  private CodeBlock collectExpr(Parameter param) {
    if (!param.isRequired()) {
      return CodeBlock.builder().build();
    }
    return CodeBlock.of(".orElseThrow(() -> $N.apply($S))", errMissing, param.key());
  }

  private CodeBlock javadoc() {
    return CodeBlock.builder().add("Generated by <a href=\"" + PROJECT_URL + "\">javols " +
        getClass().getPackage().getImplementationVersion() +
        "</a>\n").build();
  }
}
